config/routes.rb
Podil::Application.routes.draw do
  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/search', :to => 'pages#search'

end

app/models/search.rb
class Search < ActiveRecord::Base

  include HTTParty
  base_uri 'http://query.yahooapis.com/v1/public/yql'

  def self.music_search
    self.get("", :query => {:q => "select * from music.track.search where keyword= 'tik tok'",
                            :format => 'json' })
  end

  def self.music_hash
    self.music_search.parsed_response["query"]["results"]["result"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'rubygems'
  require 'youtube_g'
  require 'musix_match'
  require 'mbws'
  require 'last_fm'
  require 'twitter'

  def home
    client   = YouTubeG::Client.new
    @youtube = client.videos_by(:tags => ['music'],:time => :today, :per_page => 4)
  end

  def contact
    @title = "Contact Us"
  end

  def about
    @title = "Who are we?"
  end

  def help
    @title = "Hop hop and away!"
  end

  def search
    @title    = "Results"
    search    = params['q']
    @quer     = search
    client    = YouTubeG::Client.new
    @youtube  = client.videos_by(:query => "#{search}", :page => 1, :per_page => 1)
    @msearch  = Search.music_hash
    lfm       = LastFM.new()
    @similar  = lfm.artist.getSimilar(:artist => search, :limit => 5)
    @simitr   = lfm.track.getSimilar(:track => 'tik tok', :artist => 'ke$ha', :limit => 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns a title for every page
  def title
    base_title = "Podil"
    if @title.nil?
      base_title
    else
      "#{@title} - #{base_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
      <nav class="footer">
      <div class="footer">
        <center>
      <ul>
        <li><a href="http://gduplessy.posterous.com" target="_blank">Made by Georges Duplessy</a></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="http://podil.heroku.com/" layout="button_count" show_faces="false" width="450"></fb:like></li>
        <li><a href="http://twitter.com/share" class="twitter-share-button" data-url="http://podil.heroku.com/" data-text="Get lyrics for your Music! Check this out!" data-count="horizontal" data-via="gduplessy">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></li>
      </ul>
    </center>
  </div>
  </nav>
      </footer>

app/views/layouts/_header.html.erb
<header>
<% logo = image_tag("logo.png", :alt => "Podil", :class => "round") %>
<center><%= link_to logo, root_path %></center>
      </header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/_tracking.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7596896-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  <meta property="fb:app_id" content="171535432887454" />
  <script type="text/javascript">
    var GoSquared={};
    GoSquared.acct = "GSN-002382-H";
    (function(w){
        function gs(){
            w._gstc_lt=+(new Date); var d=document;
            var g = d.createElement("script"); g.type = "text/javascript"; g.async = true; g.src = "//d1l6p2sc9645hc.cloudfront.net/tracker.js";
            var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(g, s);
        }
        w.addEventListener?w.addEventListener("load",gs,false):w.attachEvent("onload",gs);
    })(window);
</script>
<script type='text/javascript'> var mp_protocol = (('https:' == document.location.protocol) ? 'https://' : 'http://'); document.write(unescape('%3Cscript src="' + mp_protocol + 'api.mixpanel.com/site_media/js/api/mixpanel.js" type="text/javascript"%3E%3C/script%3E')); </script> <script type='text/javascript'> try {  var mpmetrics = new MixpanelLib('84563537f73f73548f04ccc83b455d3c'); } catch(err) { null_fn = function () {}; var mpmetrics = {  track: null_fn,  track_funnel: null_fn,  register: null_fn,  register_once: null_fn, register_funnel: null_fn }; } </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <%= render 'layouts/tracking' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
            <section class="round">
        <%= yield %>
        </section>
        <%= render 'layouts/footer' %>
          </div>
  </body>
</html>

app/views/pages/about.html.erb
<p><h2>What is this?</h2>
Hmm..not sure what it is yet. <br />
But basically it is a website that helps you with your melomania!</p>

<p><h2>How?!</h2>
Quite simple! You have a music that you like? 
Type it in and you will, or atleast you should, get back the lyrics of that song, other songs by this artist and similar songs by other people!
Basically it is your own polyvalent DJ or, as I like to call it, "Pandora on Crack"</p>

<p><h2>Why should I use it?</h2>
Because you're cool! No, really. That's the only reason I could come up with!<br />
And of course because it's cool and simple and did I say cool?</p>

app/views/pages/contact.html.erb
<h1>Georges Duplessy</h1>
<p>I can be reached using any of those methods: </p>
<ul>
  <li><a href="http://twitter.com/gduplessy">Twitter - @gduplessy</a></li>
  <li><a href="http://gduplessy.posterous.com">Through my posterous blog</a></li>
</ul>

app/views/pages/help.html.erb
<h2>How do I use it?</h2>
Pretty simple really, just type the name of an artist or a song in the search box and press the button on the right!<br />
And off you go. Now you will get the most popular video for that query on youtube along with, mostly correct, lyrics for that song.<br />

<h2>Who are you?</h2>
A college student hacking his way towards a B.S. in Computer Science.<br />
I'm currently a freshman, and you can follow me on <a href="http://www.twitter.com/gduplessy">twitter</a> or read <a href="http://gduplessy.posterous.com">my blog</a>

app/views/pages/home.html.erb
<% form_tag(search_path, :method => 'get') do %>
  <center>
    <span id="name" style="visibility:hidden;"><%= label_tag :q, "Search for (Artist, song): " %></span>
    <div  type="text" onmouseover="document.getElementById('name').style .visibility='visible'" onmouseout="document.getElementById('name').style. visibility='hidden'">
      <%= text_field_tag :q, 'Tik Tok', :size => 75 %>
    </div>
    <%= submit_tag 'Search' %>
  </center>
<% end %>

app/views/pages/search.html.erb
<% require 'rubygems' %>
<% require 'musix_match' %>
<% require 'RedCloth' %>
<% require 'twitter' %>

<% form_tag(search_path, :method => 'get') do %>
  <center>
    <span id="name" style="visibility:hidden;"><%= label_tag :q, "Artist Or Song: " %></span>
    <div  type="text" onmouseover="document.getElementById('name').style .visibility='visible'" onmouseout="document.getElementById('name').style. visibility='hidden'">
      <%= text_field_tag :q, '', :size => 75 %>
    </div>
    <%= submit_tag 'Search' %>
  </center>
<% end %>
<br />
<div class="twitter">
   <% twsearch  = Twitter::Search.new %>
   <% twsearch.containing(params['q']).result_type("recent").per_page(5).each do |r| %>
     <% twat = "<a href='http://www.twitter.com/#{r.from_user}'>@#{r.from_user}</a>: #{r.text}" %>
     <% twitter = RedCloth.new(twat).to_html %>
     <%=raw twitter %>
   <% end %>
 </div>
 <br />
<div class="video">
  <% @youtube.videos.each do |v| %>
    <% if v.embeddable?  %>
      <% title_track = v.title%>
     <p><object width="425" height="350"> 
        <param name="movie" value="<%= v.embed_url %>">
       </param> 
       <param name="wmode" value="transparent">
        </param> 
       <embed src="<%= v.embed_url %>" type="application/x-shockwave-flash" wmode="transparent" width="425" height="350">
       </embed> 
     </object><br />
     <a href="http://www.youtube.com/watch?v=<%= v.unique_id %>"><%= v.title %></a></p>
   <% @title = v.title %>
 </div>
 <% end %>
 <% end %>
 <div id="disqus_thread"></div>
 <div class="fb">
   <div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=171535432887454&amp;amp;xfbml=1"></script><fb:comments numposts="10" width="425" publish_feed="true"></fb:comments>
 </div>